name: Refresh Cephu Data
on:
  schedule:
  # Draait elke 5 minuten van ma t/m vr, tussen 14:00 en 22:00 UTC
    - cron: '*/5 14-22 * * 1-5'
  workflow_dispatch: # Hiermee kun je het ook handmatig starten

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run script
        run: python cephu_analysis.py
        env:
          IBKR_USER: ${{ secrets.IBKR_USER }} # Als je inloggegevens nodig hebt
      - name: Commit and push if changed
        run: |
          git config --global user.name 'Cephu Automation'
          git config --global user.email 'automation@cephu.com'
          git add index.html
          git commit -m "Auto-update market data" || exit 0
          git push
